# YOLOv8 Dataset Configuration
path: ./data/yolo
train: images/train
val: images/val

# Number of classes
nc: 29

# Class names
names:
  0: Cherry leaf
  1: Peach leaf
  2: Corn leaf blight
  3: Apple rust leaf
  4: Potato leaf late blight
  5: Strawberry leaf
  6: Corn rust leaf
  7: Tomato leaf late blight
  8: Tomato mold leaf
  9: Potato leaf early blight
  10: Apple leaf
  11: Tomato leaf yellow virus
  12: Blueberry leaf
  13: Tomato leaf mosaic virus
  14: Raspberry leaf
  15: Tomato leaf bacterial spot
  16: Squash Powdery mildew leaf
  17: grape leaf
  18: Corn Gray leaf spot
  19: Tomato Early blight leaf
  20: Apple Scab Leaf
  21: Tomato Septoria leaf spot
  22: Tomato leaf
  23: Soyabean leaf
  24: Bell_pepper leaf spot
  25: Bell_pepper leaf
  26: grape leaf black rot
  27: Potato leaf
  28: Tomato two spotted spider mites leaf
